package com.shpagat.prosto.utils

const val ADMIN = "admin"
const val SCHEDULE = "schedule"
const val USED_TICKETS = "usedTickets"
const val MAIL = "mail"
const val PHONE = "phone"
const val NAME = "name"
const val REMAINED = "remained"
const val TITLE = "title"
const val NOTES = "notes"
const val COACH = "coach"
const val PRICE = "price"
const val TIME = "time"
const val TRAININGS = "trainings"
const val PLACES = "places"
