package com.shpagat.prosto.utils

// константы
const val ADMIN = "admin"
const val USED_TICKETS = "usedTickets"
const val MAIL = "mail"
const val PHONE = "phone"
const val NAME = "name"
const val REMAINED = "remained"
const val TITLE = "title"
const val NOTES = "notes"
const val COACH = "coach"
const val PRICE = "price"
const val TIME = "time"
const val TRAININGS = "trainings"
const val PLACES = "places"

const val SCHOOL = "Школа шпагата"
const val KUNDALINI = "Кундалини йога"
const val BACK = "Здоровая спина"
const val AERO = "Aero"
const val FULL = "Full body"
const val JOGA = "Yoga balance"
const val MFR = "MFR + stretch"
const val SIMETRICA = "Simetrica"
const val PIN = "Гвоздестояние"
